apiVersion: v1
data:
  fabricinfras.netop.mgr.yaml: |
    "name:os-bm-1, ns:netop-manager, status:{\"allocated\":[{\"extern_dynamic_pools\":[\"10.4.0.1/16\"],\"machine_group_profile\":\"for-aci-cni-2\",\"mcast_subnet_pools\":[\"225.114.1.0/16\"],\"node_subnet_pools\":[\"1.100.101.1/24\"],\"service_vlan_pools\":[102]}],\"deployment_scripts\":[\"kubectl apply -f https://raw.githubusercontent.com/networkoperator/demo-cluster-manifests/test/fabric-manager/argo/os-bm-1/argo_app.yaml\"]}, status_b64:eyJhbGxvY2F0ZWQiOlt7ImV4dGVybl9keW5hbWljX3Bvb2xzIjpbIjEwLjQuMC4xLzE2Il0sIm1hY2hpbmVfZ3JvdXBfcHJvZmlsZSI6ImZvci1hY2ktY25pLTIiLCJtY2FzdF9zdWJuZXRfcG9vbHMiOlsiMjI1LjExNC4xLjAvMTYiXSwibm9kZV9zdWJuZXRfcG9vbHMiOlsiMS4xMDAuMTAxLjEvMjQiXSwic2VydmljZV92bGFuX3Bvb2xzIjpbMTAyXX1dLCJkZXBsb3ltZW50X3NjcmlwdHMiOlsia3ViZWN0bCBhcHBseSAtZiBodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vbmV0d29ya29wZXJhdG9yL2RlbW8tY2x1c3Rlci1tYW5pZmVzdHMvdGVzdC9mYWJyaWMtbWFuYWdlci9hcmdvL29zLWJtLTEvYXJnb19hcHAueWFtbCJdfQ=="
kind: ConfigMap
metadata:
  labels:
    netop-manager: fabricinfras.netop.mgr
  name: fabricinfras.netop.mgr
  namespace: netop-manager
