apiVersion: notification-ctrlr.netop-types.io/v1alpha1
kind: Notification
metadata:
  creationTimestamp: null
  name: netop-manager-system-websocket-config-configmap-core-v1
spec:
  clusterName: ocp410bf
  objRef:
    apiVersion: v1
    kind: ConfigMap
    name: websocket-config
    namespace: netop-manager-system
  serializedObj: '{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"websocket-config","namespace":"netop-manager-system","creationTimestamp":null},"data":{"serverIP":"172.18.0.2","serverPort":"8095"}}'
status:
  state: ""
