apiVersion: netop.mgr/v1
kind: FabricInfra
metadata:
  labels:
    fabric: 4.2.7f
    site: BUILDING-15-LAB
  name: hyperflex
  namespace: netop-manager
spec:
  aci:
    infra_vlan: 3901
  credentials:
    hosts:
    - 10.30.120.180
    login:
      password: dummy
      username: dummy
  fabric_type: aci
