apiVersion: v1
data:
  data: name:cko-cni-calico, ns:null, status:{"cniType":"calico","cniVersion":"3.23","managedState":"New","observedGeneration":1,"state":"Pending","upgradeStatus":{"cniUpgradeState":"None"}},
    status_b64:eyJjbmlUeXBlIjoiY2FsaWNvIiwiY25pVmVyc2lvbiI6IjMuMjMiLCJtYW5hZ2VkU3RhdGUiOiJOZXciLCJvYnNlcnZlZEdlbmVyYXRpb24iOjEsInN0YXRlIjoiUGVuZGluZyIsInVwZ3JhZGVTdGF0dXMiOnsiY25pVXBncmFkZVN0YXRlIjoiTm9uZSJ9fQ==
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    netop-manager-resource: cniops.network-function.netop-manager.io
    notification.notification-ctrlr.netop-manager.io: exclude
  name: calicogf2-cniops.network-function.netop-manager.io
  namespace: netop-manager-system
