apiVersion: notification-ctrlr.netop-types.io/v1alpha1
kind: Notification
metadata:
  creationTimestamp: null
  name: calico-system-tigera-ca-bundle-configmap-core-v1
spec:
  clusterName: calicoacicluster
  objRef:
    apiVersion: v1
    kind: ConfigMap
    name: tigera-ca-bundle
    namespace: calico-system
  serializedObj: '{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"tigera-ca-bundle","namespace":"calico-system","creationTimestamp":null},"data":{"tigera-ca-bundle.crt":"#
    certificate name: tigera-ca-private\n-----BEGIN CERTIFICATE-----\nMIIDKTCCAhGgAwIBAgIIHMtiBOvVQS0wDQYJKoZIhvcNAQELBQAwITEfMB0GA1UE\nAxMWdGlnZXJhLW9wZXJhdG9yLXNpZ25lcjAgFw0yMjExMDUwMDIwNDhaGA8yMTIy\nMTAxMjAwMjA0OVowITEfMB0GA1UEAxMWdGlnZXJhLW9wZXJhdG9yLXNpZ25lcjCC\nASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMM/HB94c+S0csSVGpQ5CkSb\nlIN3XJl28af5uR8sxUsswv1JeKjwkv9VzEDMFasS/ufBsBrJPFvS1iDhlP44SDiJ\nIDreK43TJRBNG5sr23DmNC1QFGXA6G1mMKGeVY1kbbdH/WwtVxunJ9hZt4PLo1wB\n/sz11NmA0s/5NSmJjTVEBtJgORKDzF8M6pKN6zEa/6XElgv2cLDv24Bb6HVEnE8X\nBU5KZiaUz8mypotLewhkvfK4MSyW6LivOzfvZeHs5qceNnEAI3+LroDhS6B15smy\nfq7HdlZMBtB1J/zC9UlFGfuziFvuMPkmKG3/7wcGML/JGPLD35dPy+h9SK/8XqMC\nAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O\nBBYEFED7d6ioiM9+42V9LCwsHx75XGA+MB8GA1UdIwQYMBaAFED7d6ioiM9+42V9\nLCwsHx75XGA+MA0GCSqGSIb3DQEBCwUAA4IBAQCTGAVn7pulnbPsdDS9+/5MtO3e\ntHjRv6MxwljcmvSn5D5tr0lTQU1h/3XbgFsRwRYfN6Jl+lo39Pj4KMjiH2NUxOuO\nfC3sgcclSq0Au8ESChSxnTBWMZma+lQFSv27L6vUw8CD2WbbvK6XcgNLHTzGmbjD\ngWYpOLnXER3aceJY/Y6mJMazTZO++y8uZsriXM9U2qqiBKpQrk0T51Q3eWGy5d4M\nlzlksH31OAM4QQzzpRjuntfjzoSRTkk6FPE28D41FVKIXmhkk/W72gxg9b/x1H32\nwihnP9SlU2BKmEUzHUjW6MhgWUMIcWCJCxTdXMX1VfRwPC0jo2ewdKBdoQ4W\n-----END
    CERTIFICATE-----\n\n\n"}}'
status:
  state: ""
