apiVersion: v1
data:
  data: 'name:cko-cni-calico, ns:null, status:{"cniStatus":{"ipam-scan":"error: unable
    to upgrade connection: container not found (\"calicoctl\")\n","ipam-status":"error:
    unable to upgrade connection: container not found (\"calicoctl\")\n","version":"error:
    unable to upgrade connection: container not found (\"calicoctl\")\n"},"cniType":"calico","cniVersion":"3.23","ipam":"error:
    unable to upgrade connection: container not found (\"calicoctl\")\n","managedState":"New","observedGeneration":1,"state":"Running","upgradeStatus":{"cniUpgradeState":"None"}},
    status_b64:eyJjbmlTdGF0dXMiOnsiaXBhbS1zY2FuIjoiZXJyb3I6IHVuYWJsZSB0byB1cGdyYWRlIGNvbm5lY3Rpb246IGNvbnRhaW5lciBub3QgZm91bmQgKFwiY2FsaWNvY3RsXCIpXG4iLCJpcGFtLXN0YXR1cyI6ImVycm9yOiB1bmFibGUgdG8gdXBncmFkZSBjb25uZWN0aW9uOiBjb250YWluZXIgbm90IGZvdW5kIChcImNhbGljb2N0bFwiKVxuIiwidmVyc2lvbiI6ImVycm9yOiB1bmFibGUgdG8gdXBncmFkZSBjb25uZWN0aW9uOiBjb250YWluZXIgbm90IGZvdW5kIChcImNhbGljb2N0bFwiKVxuIn0sImNuaVR5cGUiOiJjYWxpY28iLCJjbmlWZXJzaW9uIjoiMy4yMyIsImlwYW0iOiJlcnJvcjogdW5hYmxlIHRvIHVwZ3JhZGUgY29ubmVjdGlvbjogY29udGFpbmVyIG5vdCBmb3VuZCAoXCJjYWxpY29jdGxcIilcbiIsIm1hbmFnZWRTdGF0ZSI6Ik5ldyIsIm9ic2VydmVkR2VuZXJhdGlvbiI6MSwic3RhdGUiOiJSdW5uaW5nIiwidXBncmFkZVN0YXR1cyI6eyJjbmlVcGdyYWRlU3RhdGUiOiJOb25lIn19'
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    netop-manager-resource: cniops.network-function.netop-manager.io
    notification.notification-ctrlr.netop-manager.io: exclude
  name: calicoacicluster-cniops.network-function.netop-manager.io
  namespace: netop-manager-system
