apiVersion: v1
data:
  installers.netop-manager-cntrlr.netop-manager.io.yaml: |
    "name:installer-calico-cni, ns:netop-manager-system, status:{\"clusterOverview\":{\"nodes\":2,\"ns\":11,\"pods\":22,\"svc\":9},\"observedGeneration\":2,\"operatorStatus\":\"Running\",\"state\":\"MonitoringNF\"}, status_b64:eyJjbHVzdGVyT3ZlcnZpZXciOnsibm9kZXMiOjIsIm5zIjoxMSwicG9kcyI6MjIsInN2YyI6OX0sIm9ic2VydmVkR2VuZXJhdGlvbiI6Miwib3BlcmF0b3JTdGF0dXMiOiJSdW5uaW5nIiwic3RhdGUiOiJNb25pdG9yaW5nTkYifQ=="
kind: ConfigMap
metadata:
  labels:
    netop-manager-resource: installers.netop-manager-cntrlr.netop-manager.io
  name: calicoacicluster-installers.netop-manager-cntrlr.netop-manager.io
  namespace: 
