apiVersion: notification-ctrlr.netop-types.io/v1alpha1
kind: Notification
metadata:
  creationTimestamp: null
  name: calico-system-tigera-ca-bundle-configmap-core-v1
spec:
  clusterName: calicoacicluster
  objRef:
    apiVersion: v1
    kind: ConfigMap
    name: tigera-ca-bundle
    namespace: calico-system
  serializedObj: '{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"tigera-ca-bundle","namespace":"calico-system","creationTimestamp":null},"data":{"tigera-ca-bundle.crt":"#
    certificate name: tigera-ca-private\n-----BEGIN CERTIFICATE-----\nMIIDKTCCAhGgAwIBAgIIT/ncjUOf6vUwDQYJKoZIhvcNAQELBQAwITEfMB0GA1UE\nAxMWdGlnZXJhLW9wZXJhdG9yLXNpZ25lcjAgFw0yMjExMDQxOTE3NThaGA8yMTIy\nMTAxMTE5MTc1OVowITEfMB0GA1UEAxMWdGlnZXJhLW9wZXJhdG9yLXNpZ25lcjCC\nASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALwk+RkSipBinZnOs6CLs3Ny\nDvy7M8ujnfddsrZnuBqG0+C8qZAkO9IAMFloCm40Jtv8KitC3pMQPTpkKj3ZZd39\n0aPbV4Tm7rKdwMIM9G9gc6+l2USJpxtok2H/Ut/Sqs6qpKEM7tAYkQz/jNuG0JvL\nciBcOE/wISti3szhYs7PqNPgLzbP/IcAMtoeU5eYrZ7iisInqZ4Knr8tLysI+ih/\nrIemKLFMiTZN+ri468OLtwZb1wgHksqYTcGWQVOri1BceSp5r2fPmHE3ELorDHq3\nTrpLH77v0dNP0dYEhEiEJ1ZXTZaI+0wKpHV/B97Yi0rY3Q9fQayopX6kuVZwZiEC\nAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O\nBBYEFOukfA6CjzUApfzfNNqsePzMat0+MB8GA1UdIwQYMBaAFOukfA6CjzUApfzf\nNNqsePzMat0+MA0GCSqGSIb3DQEBCwUAA4IBAQAofnFzoRboqEFjPRCpYkkdQ3Qq\nq5wVSXM8LwFgLO7+li9SgXspTa9TpRFqf6apI6JixM6pKdkI5i4WDuD0M9JV9vF4\nU//SyMr1qBB5utoLI81AFWjxxiucNdBqBdJm8GUXZVt5WoQ98MJIniX9nwmlm6hx\nzPjYh1Zc1qBB3XQkcbJ7cTTvwlZfIKUgG/gAcCjxhh0uK++pyXrXuaxByD8Ihu4g\nZwKPyGea5ugRQXq3pmNcTPbOcF0tvu+HiEKUu3Jak5Bmc0GkQVvN0JxUZ74VEBJi\nuvt7PTLiy7wtkys+P90ltFRtyHiC7ppzKCBSWLJOnojD5/RbkDG2lCfupQDF\n-----END
    CERTIFICATE-----\n\n\n"}}'
status:
  state: ""
