apiVersion: notification-ctrlr.netop-types.io/v1alpha1
kind: Notification
metadata:
  creationTimestamp: null
  name: netop-manager-system-kube-root-ca.crt-configmap-core-v1
spec:
  clusterName: calicoacicluster
  objRef:
    apiVersion: v1
    kind: ConfigMap
    name: kube-root-ca.crt
    namespace: netop-manager-system
  serializedObj: '{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"kube-root-ca.crt","namespace":"netop-manager-system","creationTimestamp":null},"data":{"ca.crt":"-----BEGIN
    CERTIFICATE-----\nMIIC/jCCAeagAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl\ncm5ldGVzMB4XDTIyMTAyMDIwMTI1MloXDTMyMTAxNzIwMTI1MlowFTETMBEGA1UE\nAxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKiN\nkkdfpMzcFGVPLAx4PUky/2hFObVhlXiOel3Uoz5Lii5Rtsvvuo/gOSgbrY42Q/1M\nBWn5y83EPie4SVGZA7ZJViPB5iau7ddKuXcesBfCyhh7duqPqP+/brpqm9jepiOe\ndvoRuMHsdGerHmcMJvMpxUmADHJEVTV87yhy4blci6xlEWWVhAU6qLC3n2iN3m+o\nRXR680xZWUnd18Sn+zqIyR6aLdWsmKl+M+YXpigLYTXyONOqRD3XyJVzNWeXl60Q\nPA0Qmf95JtpSxut1eL+c/y1drQGss36Sp+xRw7CPxQgc9pwvOBaCbY5GSuBheWYn\nQgOU6f88GjVezJ4ndPcCAwEAAaNZMFcwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB\n/wQFMAMBAf8wHQYDVR0OBBYEFP8ooWLrcJp1zDYCySvfAQVcf9XFMBUGA1UdEQQO\nMAyCCmt1YmVybmV0ZXMwDQYJKoZIhvcNAQELBQADggEBAFL6tL5XCTr8nx9sAbp3\nhKv8JYAkxj60EC1/TAeo6OeqWvfONHFdabcQPnNvHRvEIDu0SSu+OobbamUatO1s\neYJEVVSjO9c8BOnmKbML4iBqhNGWkG0y+F/3hvpDQ/PDAmEz5Jaw1vE0yTVC/ya2\nzrqpvsOWSnXa/PfO6KpEblNhtyJnxGNdTCZp/Rfk5lIbt53ESk5F45TmDpK8ZBb1\nUChK6AZ2z0izoBRPuJ6/lNseOwBPd5XZpXct8pbY/f/4HFtnsXFh5hV7w6IweQOW\nfagbzfObaVvhjJODO5TiE5r43o6Be7onL8ib8QpVwk/TUP/yNzyQ3ScSW88/uqqQ\n7i8=\n-----END
    CERTIFICATE-----\n"}}'
status:
  state: ""
