apiVersion: netop.mgr/v1
kind: ClusterProfile
metadata:
  name: acicnicluster2
  namespace: netop-manager
spec:
  cluster_input:
    profile:
      cni: kubernetes-1.22
      ingress: smm
      loadbalancer: fabric
      monitoring: prometheus
      service_mesh: smm
  selector:
    matchLabels:
      distro: kubernetes
      location: on-prem
      pod_network: aci
