apiVersion: v1
data:
  installers.netop-manager-cntrlr.netop-manager.io.yaml: |
    "name:sample-installer, ns:netop-manager-system, status:{\"clusterOverview\":{\"nodes\":\"2\",\"ns\":\"17\",\"pods\":\"43\",\"svc\":\"34\"},\"observedGeneration\":1,\"state\":\"SentryMode\"}, status_b64:eyJjbHVzdGVyT3ZlcnZpZXciOnsibm9kZXMiOiIyIiwibnMiOiIxNyIsInBvZHMiOiI0MyIsInN2YyI6IjM0In0sIm9ic2VydmVkR2VuZXJhdGlvbiI6MSwic3RhdGUiOiJTZW50cnlNb2RlIn0="
kind: ConfigMap
metadata:
  labels:
    netop-manager-resource: installers.netop-manager-cntrlr.netop-manager.io
  name: bm2calico-installers.netop-manager-cntrlr.netop-manager.io
  namespace: 
