apiVersion: v1
kind: Secret
metadata:
  name: repo-demo-cluster-manifests
  namespace: netop-manager-system
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/networkoperator/demo-cluster-manifests.git
  password: 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
  username: networkoperator-gittest
  proxy: http://proxy.esl.cisco.com:80
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netop-manager
  namespace: netop-manager-system
spec:
  destination:
    namespace: netop-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: workload/config/bm2acicni/
    repoURL: https://github.com/networkoperator/demo-cluster-manifests
    targetRevision: sumit-test-1
    directory:
      exclude: '*.tar.gz'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Replace=true