apiVersion: v1
data:
  fabricinfras.netop.mgr.yaml: |
    "name:k8s-bm-2, ns:netop-manager, status:{\"allocated\":[{\"external_subnets\":[\"10.3.0.1/16\",\"10.4.0.1/16\"],\"internal_subnets\":[\"1.100.101.1/16\",\"2.100.101.1/16\"],\"machine_group_profile\":\"for-aci-cni\",\"mcast_subnets\":[\"225.114.0.0/16\"],\"vlans\":[101,102]}],\"deployment_scripts\":[\"kubectl apply -f https://raw.githubusercontent.com/networkoperator/demo-cluster-manifests/sumit-test-1/fabric-manager/argo/k8s-bm-2/argo_app.yaml\"],\"ready\":true}, status_b64:eyJhbGxvY2F0ZWQiOlt7ImV4dGVybmFsX3N1Ym5ldHMiOlsiMTAuMy4wLjEvMTYiLCIxMC40LjAuMS8xNiJdLCJpbnRlcm5hbF9zdWJuZXRzIjpbIjEuMTAwLjEwMS4xLzE2IiwiMi4xMDAuMTAxLjEvMTYiXSwibWFjaGluZV9ncm91cF9wcm9maWxlIjoiZm9yLWFjaS1jbmkiLCJtY2FzdF9zdWJuZXRzIjpbIjIyNS4xMTQuMC4wLzE2Il0sInZsYW5zIjpbMTAxLDEwMl19XSwiZGVwbG95bWVudF9zY3JpcHRzIjpbImt1YmVjdGwgYXBwbHkgLWYgaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL25ldHdvcmtvcGVyYXRvci9kZW1vLWNsdXN0ZXItbWFuaWZlc3RzL3N1bWl0LXRlc3QtMS9mYWJyaWMtbWFuYWdlci9hcmdvL2s4cy1ibS0yL2FyZ29fYXBwLnlhbWwiXSwicmVhZHkiOnRydWV9"
kind: ConfigMap
metadata:
  labels:
    netop-manager: fabricinfras.netop.mgr
  name: fabricinfras.netop.mgr
  namespace: netop-manager
