apiVersion: v1
data:
  fabricinfras.netop.mgr.yaml: |
    "name:k8s-bm-2, ns:netop-manager, status:{\"allocated\":[{\"cluster_profile\":\"calicoacicluster\",\"context\":{\"l3out\":{},\"vrf\":{}},\"internal_subnets\":[\"1.100.101.1/16\"],\"machine_group_profile\":\"for-calico-cni\",\"remote_as_numbers\":[64515],\"vlans\":[101]}],\"deployment_scripts\":[\"kubectl apply -f https://raw.githubusercontent.com/networkoperator/demo-cluster-manifests/sumit-test-1/fabric-manager/argo/k8s-bm-2/argo_app.yaml\"],\"ready\":true}, status_b64:eyJhbGxvY2F0ZWQiOlt7ImNsdXN0ZXJfcHJvZmlsZSI6ImNhbGljb2FjaWNsdXN0ZXIiLCJjb250ZXh0Ijp7Imwzb3V0Ijp7fSwidnJmIjp7fX0sImludGVybmFsX3N1Ym5ldHMiOlsiMS4xMDAuMTAxLjEvMTYiXSwibWFjaGluZV9ncm91cF9wcm9maWxlIjoiZm9yLWNhbGljby1jbmkiLCJyZW1vdGVfYXNfbnVtYmVycyI6WzY0NTE1XSwidmxhbnMiOlsxMDFdfV0sImRlcGxveW1lbnRfc2NyaXB0cyI6WyJrdWJlY3RsIGFwcGx5IC1mIGh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9uZXR3b3Jrb3BlcmF0b3IvZGVtby1jbHVzdGVyLW1hbmlmZXN0cy9zdW1pdC10ZXN0LTEvZmFicmljLW1hbmFnZXIvYXJnby9rOHMtYm0tMi9hcmdvX2FwcC55YW1sIl0sInJlYWR5Ijp0cnVlfQ=="
kind: ConfigMap
metadata:
  labels:
    netop-manager: fabricinfras.netop.mgr
  name: fabricinfras.netop.mgr
  namespace: netop-manager
