apiVersion: netop.mgr/v1
kind: MachineGroupProfile
metadata:
  labels:
    computes: NOVA
    distro: K8S-1.21
    location: ON-PREM
    network-infra: ACI
    pod-network: ACI-CNI
  name: k8s-1.21
  namespace: netop-manager
spec:
  selector:
    matchLabels:
      fabric: 4.2.7f
      site: BUILDING-15-LAB
