apiVersion: netop.mgr/v1
kind: FabricInfra
metadata:
  creationTimestamp: "2022-06-22T23:23:52Z"
  generation: 4
  labels:
    fabric: on-prem-dev-infra
    site: bldg-15-lab
  managedFields:
  - apiVersion: netop.mgr/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:fabric: {}
          f:site: {}
      f:spec:
        .: {}
        f:aci:
          .: {}
          f:extern_static_pools: {}
          f:infra_vlan: {}
          f:kubeapi_vlan_pools: {}
          f:mcast_subnet_pools: {}
          f:node_svc_subnet_pools: {}
          f:service_vlan_pools: {}
        f:credentials:
          .: {}
          f:hosts: {}
          f:login:
            .: {}
            f:password: {}
            f:username: {}
        f:fabric_type: {}
    manager: kubectl-create
    operation: Update
    time: "2022-06-22T23:23:52Z"
  - apiVersion: netop.mgr/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:deployment_scripts: {}
    manager: manager
    operation: Update
    subresource: status
    time: "2022-06-22T23:23:59Z"
  name: k8s-bm-1
  namespace: netop-manager
  resourceVersion: "13647548"
  uid: 04f21038-790a-46ac-a07e-f6165ba3ed73
spec:
  aci:
    extern_static_pools:
    - 20.4.0.1/16
    infra_vlan: 4093
    kubeapi_vlan_pools:
    - 103
    mcast_subnet_pools:
    - 225.115.0.0/16
    node_svc_subnet_pools:
    - 20.5.0.1/16
    service_vlan_pools:
    - 104
  credentials:
    hosts:
    - 10.30.120.140
    login:
      password: dummy
      username: dummy
  fabric_type: aci
status:
  deployment_scripts:
  - kubectl apply -f https://raw.githubusercontent.com/networkoperator/demo-cluster-manifests/test/fabric-manager/argo/k8s-bm-1/argo_app.yaml
