apiVersion: v1
data:
  clusterprofile_overrides: "cluster_input:\n  aci_cni_config:\n    aci_config:\n
    \     vmm_domain:\n        encap_type: vxlan\n        mcast_range:\n            start:
    225.114.1.1\n            end: 225.114.255.255\n    kube_config:\n      ovs_memory_limit:
    0.75Gi\n      image_pull_policy: Always\n      allow_pods_external_access: True\n
    \   logging:\n      controller_log_level: debug\n      hostagent_log_level: debug\n
    \     opflexagent_log_level: debug\n    net_config:\n      extern_static: 10.4.0.1/16\n
    \     service_vlan: 102\n      node_svc_subnet: 10.5.0.1/16\n  registry:\n    image_prefix:
    quay.io/noirolabs\n    image_pull_secret: noiro-docker-registry-secret\n    network_operator_version:
    demo-test\n  service_mesh_config:\n    mesh_id: mesh1\n    role: Primary\n    kubeconfig:
    https://127.0.0.1:6443 \n  monitoring_config:\n    monitoring_type: prometheus\n
    \   remote_write_ip: 1.1.1.1\n    remote_write_port: 10000\n"
kind: ConfigMap
metadata:
  labels:
    distro: kubernetes
    location: on-prem
    pod_network: aci
  name: acicnicluster
  namespace: netop-manager
