apiVersion: netop.mgr/v1
kind: ClusterProfile
metadata:
  name: acicnicluster
  namespace: netop-manager
spec:
  cluster_input:
    profile:
      cni: kubernetes-1.22
      ingress: smm
      loadbalancer: fabric
      monitoring: prometheus
      service_mesh: smm
  selector:
    matchLabels:
      cluster: aci-cni
      distro: kubernetes
      location: on-prem
      pod-network: aci
