apiVersion: v1
data:
  clusterprofile_overrides: |
    cluster_input:
      aci_cni_config:
        aci_config:
          vmm_domain:
            encap_type: vxlan
            mcast_range:
                start: 225.114.1.1
                end: 225.114.255.255
        kube_config:
          ovs_memory_limit: 0.75Gi
          image_pull_policy: Always
        logging:
          controller_log_level: debug
          hostagent_log_level: debug
          opflexagent_log_level: debug
        net_config:
          extern_static: 10.4.0.1/16
          service_vlan: 102
          node_svc_subnet: 10.5.0.1/16
      registry:
        image_prefix: quay.io/noirolabs
        image_pull_secret: noiro-docker-registry-secret
        network_operator_version: demo-test
      net_config:
        node_subnet: 1.100.101.1/24
        pod_subnet: 10.6.0.1/16
        extern_dynamic: 10.3.0.1/16
        kubeapi_vlan: 101
        cluster_svc_subnet: 10.96.0.0/12
      service_mesh_config:
        name: bm2acicni
        network: network1
        mesh_id: mesh1
        role: Primary
        kubeconfig: https://github.com/networkoperator/demo-clusters/tree/kiran/aci-cni-cluster
      monitoring_config:
        monitoring_type: prometheus
        remote_write_ip: 3.237.37.136
        remote_write_port: 32307
      cko_proxy_config:
        http_proxy: http://proxy.esl.cisco.com:80
        https_proxy: http://proxy.esl.cisco.com:80
        no_proxy: 10.96.0.1
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-15T21:05:16Z"
  labels:
    distro: kubernetes
    location: on-prem
    pod_network: aci
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:clusterprofile_overrides: {}
      f:metadata:
        f:labels:
          .: {}
          f:distro: {}
          f:location: {}
          f:pod_network: {}
    manager: kubectl-create
    operation: Update
    time: "2022-07-15T21:05:16Z"
  name: bm2acicni
  namespace: netop-manager
  resourceVersion: "2323"
  uid: 2611a44b-daae-492a-9f6e-d1c51e83c14d
