apiVersion: netop.mgr/v1
kind: ClusterProfile
metadata:
  name: bm2acicni
  namespace: netop-manager
spec:
  cni: cko-unmanaged
  selector:
    matchLabels:
      cluster: aci-cni
      distro: kubernetes
      location: on-prem
      pod-network: aci
