apiVersion: netop.mgr/v1
kind: ClusterProfile
metadata:
  name: calicoacicluster
  namespace: netop-manager
spec:
  cni: cko-calico
  selector:
    matchLabels:
      cluster: calico-cni
      distro: kubernetes
      location: on-prem
      pod-network: calico
