apiVersion: v1
data:
  machinegroupprofile_overrides: |
    pod_subnet: 10.6.0.1/16
kind: ConfigMap
metadata:
  labels:
    cluster: aci-cni
    fabric: on-prem-dev-infra
    site: bldg-15-lab
  name: for-aci-cni
  namespace: netop-manager
