apiVersion: netop.mgr/v1
kind: MachineGroupProfile
metadata:
  labels:
    cluster: calico-cni
    distro: kubernetes
    location: on-prem
    pod-network: calico
  name: for-calico-cni
  namespace: netop-manager
spec:
  aep: bm-srvrs-aep
  l3out:
    external_networks:
    - sauto_l3out-3_epg
    name: sauto_l3out-3
    svi:
      int_prof_name: sauto_l3out-3_int_prof
      node_profile_name: sauto_l3out-3_node_prof
  physical_domain:
    domain: bm-srvrs-calico-pd
  selector:
    matchLabels:
      fabric: on-prem-dev-infra
      site: bldg-15-lab
  server_count: 3
  vrf:
    name: sauto_l3out-3_vrf
    tenant: common
