apiVersion: netop.mgr/v1
kind: FabricInfra
metadata:
  labels:
    fabric: on-prem-dev-infra
    site: bldg-15-lab
  name: k8s-bm-2
  namespace: netop-manager
spec:
  aci:
    extern_static_pools:
    - 20.4.0.1/16
    infra_vlan: 4093
    kubeapi_vlan_pools:
    - 103
    mcast_subnet_pools:
    - 225.115.0.0/16
    node_svc_subnet_pools:
    - 20.5.0.1/16
    service_vlan_pools:
    - 104
  credentials:
    hosts:
    - 10.30.120.140
    login:
      password: dummy
      username: dummy
  fabric_type: aci
