apiVersion: netop.mgr/v1
kind: FabricInfra
metadata:
  labels:
    fabric: on-prem-dev-infra
    site: bldg-15-lab
  name: k8s-bm-2
  namespace: netop-manager
spec:
  aci:
    extern_dynamic_pools:
    - 10.3.0.1/16
    extern_static_pools:
    - 10.4.0.1/16
    infra_vlan: 4093
    kubeapi_vlan_pools:
    - 101
    mcast_subnet_pools:
    - 225.114.0.0/16
    node_subnet_pools:
    - 1.100.101.1/16
    node_svc_subnet_pools:
    - 10.5.0.1/16
    service_vlan_pools:
    - 102
  credentials:
    hosts:
    - 10.30.120.140
    login:
      password: dummy
      username: dummy
  fabric_type: aci
