apiVersion: netop.mgr/v1
kind: FabricInfra
metadata:
  labels:
    fabric: on-prem-dev-infra
    site: bldg-15-lab
  name: k8s-bm-2
  namespace: netop-manager
spec:
  aci:
    external_subnets:
    - 20.3.0.1/16
    - 20.4.0.1/16
    infra_vlan: 4093
    internal_subnets:
    - 10.6.0.1/16
    - 20.2.0.1/16
    - 20.5.0.1/16
    mcast_subnets:
    - 225.115.0.0/16
    vlans:
    - 103
    - 104
  credentials:
    hosts:
    - 10.30.120.140
    login:
      password: dummy
      username: dummy
  fabric_type: aci
