apiVersion: netop.mgr/v1
kind: FabricInfra
metadata:
  labels:
    fabric: on-prem-dev-infra
    site: bldg-15-lab
  name: k8s-bm-2
  namespace: netop-manager
spec:
  aci:
    infra_vlan: 4093
  credentials:
    hosts:
    - 10.30.120.140
    login:
      password: dummy
      username: dummy
  fabric_type: aci
